version: '3.9'

services:
  
  mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    ports:
      - "3306:3306"
    volumes:
      - ./dev/mysql:/var/lib/mysql

  mongodb:
    image: mongo:4.4.2-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./dev/mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dev/rabbitmq:/var/lib/rabbitmq