version: '3.9'

services:
  
  mysql:
    image: mysql:8.0.23
    hostname: mysql
    environment:
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./dev/mysql:/var/lib/mysql

  mongodb:
    image: mongo:4.4.2-bionic
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./dev/mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    image: parlaga/server
    hostname: server
    environment:
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=mysql
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - rabbitmq
    command: >
      bash -c "./wait-for-it.sh mysql:3306 -t 0
      && ./wait-for-it.sh rabbitmq:5672 -t 0 -- node src/server.js"

  weatherservice:
    image: parlaga/weatherservice
    hostname: weatherservice
    ports:
      - 9090:9090

  toposervice:
    image: parlaga/toposervice
    hostname: toposervice
    ports:
      - 8080:8080
    environment: 
      - MONGO_DB_HOST=mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=topo
    depends_on:
      - mongodb

  # Wheatherservice services
  planner:
    image: parlaga/planner
    hostname: planner
    environment:
      - TOPOSERVICE_HOST=toposervice
      - TOPOSERVICE_PORT=8080
      - GRPC_HOST=weatherservice
      - GRPC_PORT=9090
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_PORT=5672
    ports:
      - 8081:8080
    depends_on: 
      - rabbitmq
      - toposervice
      - weatherservice