version: '3.9'

services:
  
  mysql:
    image: mysql:8.0.22
    env_file:
      - prod.env
    ports:
      - "3306:3306"
    volumes:
      - ./dev/mysql:/var/lib/mysql

  mongodb:
    image: mongo:4.4.2-bionic
    env_file:
      - prod.env
    ports:
      - "27017:27017"
    volumes:
      - ./dev/mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - prod.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dev/rabbitmq:/var/lib/rabbitmq

  server:
    image: parlaga/server
    env_file:
      - prod.env
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - rabbitmq
    command: >
      bash -c "./wait-for-it.sh mysql:3306 -t 0
      && ./wait-for-it.sh rabbitmq:5672 -t 0 -- node src/server.js"

  weatherservice:
    image: parlaga/weatherservice
    ports:
      - 9090:9090
    command: >
      bash -c "node src/server.js"

  toposervice:
    image: parlaga/toposervice
    ports:
      - 8080:8080
    env_file:
      - prod.env
    depends_on:
      - mongodb

  # Wheatherservice services
  planner:
    image: parlaga/planner
    ports:
      - 8080:8080
    depends_on: 
      - rabbitmq
      - toposervice
      - weatherservice