apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      restartPolicy: Always
      containers:
      - name: mongodb
        image: mongo:4.4.2-bionic
        env:
          - name: MONGO_INITDB_DATABASE
            value: topoDB
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
        ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
---

## service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
    - name: "27018"
      port: 27018
      targetPort: 27018
    - name: "27019"
      port: 27019
      targetPort: 27019
  selector:
    app: mongodb
  type: ClusterIP