
## deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.22
        env:
          - name: MYSQL_DATABASE
            value: eoloplantsDB
          - name: MYSQL_ROOT_PASSWORD
            value: password
---

## service
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: ClusterIP
