apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: planner
  name: planner
spec:
  containers:
    - env:
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://weatherservice:9090
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: TOPO_HOST
          value: toposervice
        - name: TOPO_PORT
          value: "8080"
      image: oscarsotosanchez/planner:v1.0
      name: planner
      resources: {}
  restartPolicy: OnFailure
status: {}
