apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  containers:
    - args:
        - bash
        - -c
        - ' ./wait-for-it.sh mysql:3306 -- ./wait-for-it.sh rabbitmq:5672 -- node src/server.js'
      env:
        - name: MYSQL_DB
          value: eoloplantsDB
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASS
          value: password
        - name: MYSQL_USER
          value: root
        - name: RABBITMQ_URL
          value: amqp://root:password@rabbitmq
      image: oscarsotosanchez/server:v1.0
      name: server
      ports:
        - containerPort: 3000
      resources: {}
  restartPolicy: OnFailure
status: {}
