apiVersion: apps/v1
kind: Deployment
metadata:
  name: toposervice
spec:
  selector:
    matchLabels:
      app: toposervice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: toposervice
    spec:
      containers:
      - name: toposervice
        image: oscarsotosanchez/toposervice:v1.0
        env:
        - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
          value: admin
        - name: SPRING_DATA_MONGODB_DATABASE
          value: topoDB
        - name: SPRING_DATA_MONGODB_HOST
          value: mongodb
        - name: SPRING_DATA_MONGODB_PASSWORD
          value: password
        - name: SPRING_DATA_MONGODB_PORT
          value: "27017"
        - name: SPRING_DATA_MONGODB_USERNAME
          value: root
---

## service
apiVersion: v1
kind: Service
metadata:
  name: toposervice
spec:
  ports:
  - port: 8080
  selector:
    app: toposervice
  type: ClusterIP