## deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherservice-deployment
spec:
  selector:
    matchLabels:
      app: weatherservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: weatherservice
    spec:
      restartPolicy: Always
      containers:
      - env:
        - name: GRPC_HOST
          value: 0.0.0.0
        - name: GRPC_PORT
          value: "9090"
        image: oscarsotosanchez/weatherservice:v1.0
        name: weatherservice
        ports:
        - containerPort: 9090
---

## service
apiVersion: v1
kind: Service
metadata:
  name: weatherservice-service
  labels:
    app: weatherservice
spec:
  ports:
  - port: 9090
  selector:
    app: weatherservice
  type: ClusterIP